import { db } from '@/lib/db';
import { courses, categories } from '@/lib/db/schema';
import { eq, desc } from 'drizzle-orm';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import {
  ArrowRight,
  Brain,
  Code,
  Palette,
  Rocket,
  Lightbulb,
  Target,
  Zap,
  GraduationCap,
  Play,
  Smartphone,
  Globe,
  DollarSign,
  TrendingUp,
  School,
  BookOpen,
  Users,
  Sparkles,
  Layout,
  Briefcase,
  ChevronRight,
} from 'lucide-react';
import {
  studentClassroom,
  aiRobot,
  learningPaths,
  categoryThumbnail,
} from '@/lib/imagery';

const features = [
  { icon: Brain, title: 'AI Tutor', description: 'Every learner receives a personalized experience — no matter their location, background, or prior education level.' },
  { icon: Smartphone, title: 'Access Platform', description: 'High-quality education accessible using only a phone and an internet connection.' },
  { icon: Zap, title: 'Learn Flexibly', description: 'Self-paced, career-focused digital learning that fits your schedule and your life.' },
  { icon: Target, title: 'Build Skills', description: 'Practical, income-generating digital skills that translate directly to real-world opportunities.' },
  { icon: Lightbulb, title: 'Concept Explainer', description: 'Breaks down complex topics into simple, digestible lessons tailored to each learner\'s level.' },
  { icon: Globe, title: 'Local Context Tutor', description: 'Provides real-world African examples so knowledge feels relevant, practical, and culturally resonant.' },
  { icon: Layout, title: 'Project Guide', description: 'Walks students through hands-on projects that build genuine portfolio-worthy skills.' },
  { icon: GraduationCap, title: 'Career Mentor', description: 'Prepares learners for freelancing opportunities, digital careers, and entrepreneurship pathways.' },
];

const stats = [
  { emoji: '🌍', value: '400M+', label: 'Young Africans', sub: 'will enter the workforce by 2030' },
  { emoji: '📱', value: 'Any Phone', label: 'Learn Anywhere', sub: 'using only a smartphone' },
  { emoji: '🎓', value: 'AI Lessons', label: 'Interactive Classrooms', sub: 'generated by AI tutors' },
  { emoji: '💰', value: 'Fraction', label: 'Of Traditional Cost', sub: 'compared to university fees' },
];

export default async function HomePage() {
  const featuredCourses = await db.query.courses.findMany({
    where: eq(courses.status, 'published'),
    with: { category: true },
    orderBy: [desc(courses.enrollmentCount)],
    limit: 8,
  });

  return (
    <div className="flex flex-col">
      {/* ═══════════════════════════════════════════════════════════
          HERO — Dark green full-width, centered layout
          ═══════════════════════════════════════════════════════════ */}
      <section className="relative text-white overflow-hidden">
        {/* Full-bleed background — real African student studying */}
        <img
          src={studentClassroom}
          alt=""
          aria-hidden
          className="absolute inset-0 h-full w-full object-cover"
        />
        {/* Dark overlay for legibility */}
        <div className="absolute inset-0 bg-gradient-to-b from-[#0d3d22]/95 via-[#0d3d22]/85 to-[#0d3d22]/95" />
        {/* Decorative radial glow */}
        <div className="absolute inset-0 opacity-10" style={{ backgroundImage: 'radial-gradient(circle at 30% 40%, #e8b84b 0%, transparent 50%)' }} />
        <div className="container relative mx-auto px-4 sm:px-6 pt-20 pb-24 md:pt-32 md:pb-32">
          <div className="max-w-4xl mx-auto text-center">
            {/* Badge pill */}
            <div className="inline-flex items-center gap-2 rounded-full bg-white/10 border border-white/20 px-5 py-2 text-sm font-medium text-white/90 mb-8 animate-fade-in">
              <Sparkles className="h-4 w-4 text-[#e8b84b]" />
              Turn Any Topic Into a Live AI Lesson
            </div>

            {/* H1 */}
            <h1 className="text-4xl sm:text-5xl md:text-6xl font-extrabold tracking-tight leading-tight mb-6 font-[family-name:var(--font-playfair)] animate-fade-in">
              Reimagining Education<br />for Every African Learner
            </h1>

            {/* Subheadline */}
            <p className="text-lg md:text-xl text-white/70 mb-4 max-w-3xl mx-auto leading-relaxed">
              Access world-class education using only a phone or a laptop.
            </p>

            {/* Description */}
            <p className="text-base text-white/55 mb-10 max-w-2xl mx-auto leading-relaxed">
              That is the vision behind Elimu Africa: an AI-powered educational ecosystem built to make high-quality, practical, and affordable learning accessible to every African learner.
            </p>

            {/* CTAs */}
            <div className="flex flex-col sm:flex-row justify-center gap-4 mb-14">
              <Button size="lg" asChild className="bg-[#e8b84b] hover:bg-[#d4a43e] text-[#111310] font-semibold px-8 rounded-full shadow-lg">
                <Link href="/register">
                  Start Learning Free
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
              </Button>
              <Button size="lg" variant="ghost" asChild className="border-2 border-white/70 text-white hover:bg-white/10 font-semibold rounded-full">
                <Link href="/courses">
                  Browse Courses
                </Link>
              </Button>
            </div>
          </div>

          {/* 4-pill row */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 max-w-4xl mx-auto">
            {[
              { emoji: '🤖', title: 'AI-Powered', subtitle: 'Personalized learning' },
              { emoji: '💰', title: 'Affordable', subtitle: 'Fraction of the cost' },
              { emoji: '🌍', title: 'Built for Africa', subtitle: 'African context' },
              { emoji: '⏰', title: '24/7 Access', subtitle: 'Learn anytime' },
            ].map((pill) => (
              <div key={pill.title} className="flex items-center gap-3 rounded-2xl bg-white/5 border border-white/10 px-4 py-3">
                <span className="text-2xl">{pill.emoji}</span>
                <div>
                  <p className="text-sm font-semibold text-white">{pill.title}</p>
                  <p className="text-xs text-white/50">{pill.subtitle}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ═══════════════════════════════════════════════════════════
          WAVE DIVIDER
          ═══════════════════════════════════════════════════════════ */}
      <svg viewBox="0 0 1440 80" fill="none" xmlns="http://www.w3.org/2000/svg" className="w-full -mt-px">
        <path d="M0 80V0C240 50 480 80 720 60C960 40 1200 10 1440 40V80H0Z" fill="#fafaf8" />
      </svg>

      {/* ═══════════════════════════════════════════════════════════
          FEATURE CARDS (8-up grid)
          ═══════════════════════════════════════════════════════════ */}
      <section className="py-16 md:py-24 bg-[#fafaf8]">
        <div className="container mx-auto px-4 sm:px-6">
          <div className="text-center mb-12 md:mb-16">
            <p className="text-xs font-semibold uppercase tracking-widest text-[#1a6b3c] mb-3">HOW IT WORKS</p>
            <h2 className="text-3xl md:text-5xl font-extrabold text-[#111310] mb-4 font-[family-name:var(--font-playfair)]">
              AI-Powered Learning for Every Student
            </h2>
            <p className="text-[#7a7468] text-base md:text-lg max-w-2xl mx-auto">
              Elimu Africa&apos;s intelligent AI systems create interactive environments where students don&apos;t just memorize — they actively learn, discuss, build, and solve problems.
            </p>
          </div>

          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 md:gap-6">
            {features.map((feature) => (
              <div key={feature.title} className="group rounded-2xl bg-white border border-[rgba(17,19,16,0.10)] p-5 md:p-6 hover:shadow-xl hover:-translate-y-1 transition-all duration-200 cursor-pointer">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#f0f7f3] text-[#1a6b3c] mb-4 group-hover:bg-[#1a6b3c] group-hover:text-white transition-colors">
                  <feature.icon className="h-5 w-5" />
                </div>
                <h3 className="text-sm font-semibold text-[#111310] mb-2">{feature.title}</h3>
                <p className="text-xs text-[#7a7468] leading-relaxed">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ═══════════════════════════════════════════════════════════
          AI CLASSROOMS (dark green section)
          ═══════════════════════════════════════════════════════════ */}
      <section className="relative py-16 md:py-24 bg-[#0d3d22] text-white overflow-hidden">
        <div
          className="absolute inset-0 bg-cover bg-center opacity-[0.18]"
          style={{ backgroundImage: `url(${aiRobot})` }}
          aria-hidden
        />
        <div className="absolute inset-0 bg-gradient-to-br from-[#0d3d22]/40 via-transparent to-[#0d3d22]" aria-hidden />
        <div className="container mx-auto px-4 sm:px-6 relative">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            {/* Left: text + CTA */}
            <div>
              <p className="text-xs font-semibold uppercase tracking-widest text-[#e8b84b] mb-3 flex items-center gap-2">
                <Sparkles className="h-4 w-4" />
                AI CLASSROOMS
              </p>
              <h2 className="text-3xl md:text-5xl font-extrabold text-white mb-4 font-[family-name:var(--font-playfair)]">
                Turn Any Topic Into a Live AI Lesson
              </h2>
              <p className="text-white/60 text-base md:text-lg mb-8 leading-relaxed max-w-lg">
                AI Classrooms bring any topic to life — no pre-recorded videos, no outdated content. Every lesson is generated in real-time by an AI tutor that adapts to the learner&apos;s pace and style.
              </p>
              <div className="flex flex-col sm:flex-row gap-4">
                <Button size="lg" asChild className="bg-[#e8b84b] hover:bg-[#d4a43e] text-[#111310] font-semibold px-8 rounded-full shadow-lg">
                  <Link href="/pricing">
                    Get Started
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </Link>
                </Button>
                <Button size="lg" variant="ghost" asChild className="border-2 border-white/70 text-white hover:bg-white/10 font-semibold rounded-full">
                  <Link href="/pricing">
                    See Plans
                  </Link>
                </Button>
              </div>
            </div>

            {/* Right: decorative mockup card */}
            <div className="rounded-2xl bg-white/5 border border-white/10 p-5 md:p-6 backdrop-blur-sm">
              {/* Mockup header */}
              <div className="flex items-center gap-3 mb-5 pb-4 border-b border-white/10">
                <div className="w-3 h-3 rounded-full bg-[#1a6b3c]" />
                <span className="text-xs font-medium text-white/70">AI Classroom</span>
                <span className="ml-auto text-[10px] font-semibold text-[#e8b84b] bg-[#e8b84b]/10 px-2.5 py-1 rounded-full">
                  ● Live
                </span>
              </div>
              {/* Chat bubbles */}
              <div className="space-y-4 mb-5">
                <div className="flex justify-start">
                  <div className="max-w-[80%] rounded-2xl rounded-tl-sm bg-[#1a6b3c] px-4 py-3 text-sm text-white/90">
                    Welcome to your AI Classroom! Today we&apos;ll explore how machine learning models are trained. What would you like to learn about first?
                  </div>
                </div>
                <div className="flex justify-end">
                  <div className="max-w-[80%] rounded-2xl rounded-tr-sm bg-white/10 px-4 py-3 text-sm text-white/80">
                    I&apos;d like to understand the difference between supervised and unsupervised learning.
                  </div>
                </div>
                <div className="flex justify-start">
                  <div className="max-w-[80%] rounded-2xl rounded-tl-sm bg-[#1a6b3c] px-4 py-3 text-sm text-white/90">
                    Great question! In supervised learning, we train a model on labeled data — think of it as learning from an answer key. Unsupervised learning finds patterns in unlabeled data, like discovering customer segments.
                  </div>
                </div>
              </div>
              {/* Fake input bar */}
              <div className="flex items-center gap-3 rounded-full bg-white/10 border border-white/10 px-5 py-3">
                <span className="text-sm text-white/40 flex-1">Ask a question...</span>
                <div className="w-8 h-8 rounded-full bg-[#e8b84b] flex items-center justify-center">
                  <ArrowRight className="h-4 w-4 text-[#111310]" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ═══════════════════════════════════════════════════════════
          LEARNING PATHS (4-up on beige)
          ═══════════════════════════════════════════════════════════ */}
      <section className="py-16 md:py-24 bg-[#f0ede8]">
        <div className="container mx-auto px-4 sm:px-6">
          <div className="text-center mb-12 md:mb-16">
            <p className="text-xs font-semibold uppercase tracking-widest text-[#1a6b3c] mb-3">LEARNING PATHS</p>
            <h2 className="text-3xl md:text-5xl font-extrabold text-[#111310] mb-4 font-[family-name:var(--font-playfair)]">
              Built for Africa&apos;s Digital Future
            </h2>
            <p className="text-[#7a7468] text-base md:text-lg max-w-2xl mx-auto">
              Elimu Africa is laser-focused on preparing African youth for the modern economy — skills that actually generate opportunity.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 md:gap-6">
            {learningPaths.map((path) => (
              <div key={path.number} className="group rounded-2xl overflow-hidden border border-[rgba(17,19,16,0.10)] bg-white hover:shadow-xl hover:-translate-y-1 transition-all duration-200">
                <div className="relative h-40 md:h-44 overflow-hidden">
                  <img src={path.image} alt={path.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300" />
                  <div className={`absolute inset-0 bg-gradient-to-t ${path.accent} via-black/25 to-transparent`} />
                  <span className="absolute top-3 left-3 h-9 min-w-9 px-2 rounded-lg bg-black/55 backdrop-blur-sm flex items-center justify-center text-sm font-semibold font-[family-name:var(--font-dm-mono)] text-white">
                    {path.number}
                  </span>
                </div>
                <div className="p-5 md:p-6">
                  <h3 className="text-base font-bold mb-2 text-[#111310]">{path.title}</h3>
                  <p className="text-sm text-[#7a7468] leading-relaxed mb-4">{path.description}</p>
                  <Link href="/courses" className="inline-flex items-center gap-1 text-sm font-semibold text-[#1a6b3c] hover:underline">
                    Explore Path <ChevronRight className="h-4 w-4" />
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ═══════════════════════════════════════════════════════════
          IMPACT STATS (on dark green)
          ═══════════════════════════════════════════════════════════ */}
      <section className="py-16 md:py-24 bg-[#0d3d22] text-white">
        <div className="container mx-auto px-4 sm:px-6">
          <div className="text-center mb-12 md:mb-16">
            <p className="text-xs font-semibold uppercase tracking-widest text-[#e8b84b] mb-3">THE IMPACT</p>
            <h2 className="text-3xl md:text-5xl font-extrabold text-white mb-4 font-[family-name:var(--font-playfair)]">
              The Education System Must Evolve
            </h2>
            <p className="text-white/60 text-base md:text-lg max-w-2xl mx-auto">
              Over 400 million young Africans will enter the workforce — the education system must evolve to meet them.
            </p>
          </div>

          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 md:gap-6">
            {stats.map((stat) => (
              <div key={stat.label} className="rounded-2xl bg-white/5 border border-white/10 p-6 md:p-7 text-center">
                <span className="text-3xl block mb-3">{stat.emoji}</span>
                <p className="text-3xl md:text-4xl font-bold font-[family-name:var(--font-playfair)] text-white mb-1">{stat.value}</p>
                <p className="text-sm font-semibold text-white mb-1">{stat.label}</p>
                <p className="text-xs text-white/50">{stat.sub}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ═══════════════════════════════════════════════════════════
          FEATURED COURSES
          ═══════════════════════════════════════════════════════════ */}
      <section className="py-16 md:py-24 bg-[#fafaf8]">
        <div className="container mx-auto px-4 sm:px-6">
          <div className="text-center mb-12 md:mb-16">
            <p className="text-xs font-semibold uppercase tracking-widest text-[#1a6b3c] mb-3">COURSES</p>
            <h2 className="text-3xl md:text-5xl font-extrabold text-[#111310] mb-4 font-[family-name:var(--font-playfair)]">
              Start Learning Today
            </h2>
            <p className="text-[#7a7468] text-base md:text-lg max-w-2xl mx-auto">
              Explore our catalog of AI-powered courses designed to build real-world skills.
            </p>
          </div>

          {/* Mobile: horizontal scroll, Desktop: grid */}
          <div className="flex md:grid md:grid-cols-4 gap-4 md:gap-6 overflow-x-auto scroll-x-mobile pb-2 md:pb-0">
            {featuredCourses.map((course) => (
              <Link key={course.id} href={`/courses/${course.slug}`} className="min-w-[260px] sm:min-w-[280px] md:min-w-0">
                <div className="h-full rounded-2xl bg-white border border-[rgba(17,19,16,0.10)] overflow-hidden hover:shadow-xl hover:-translate-y-1 transition-all duration-200 cursor-pointer group">
                  <div className="aspect-video bg-stone-100 relative overflow-hidden">
                    {course.thumbnail ? (
                      <img src={course.thumbnail} alt={course.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300" />
                    ) : (
                      <img
                        src={categoryThumbnail(course.category?.slug, course.slug)}
                        alt={course.title}
                        className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                      />
                    )}
                    {course.isPro && (
                      <span className="absolute top-2 right-2 bg-[#e8b84b] text-[#111310] text-[10px] font-semibold px-3 py-1 rounded-full">
                        PRO
                      </span>
                    )}
                  </div>
                  <div className="p-4">
                    <h3 className="font-bold text-sm text-[#111310] mb-1 line-clamp-2 leading-snug">{course.title}</h3>
                    {course.category && (
                      <p className="text-xs text-[#7a7468] mb-2">{course.category.name}</p>
                    )}
                    <div className="flex items-center gap-1">
                      <span className="text-sm font-bold text-[#e8b84b]">{((course.rating ?? 0) / 100).toFixed(1)}</span>
                      <div className="flex">
                        {Array.from({ length: 5 }).map((_, i) => (
                          <svg key={i} className={`h-3 w-3 ${i < Math.round((course.rating ?? 0) / 100) ? 'fill-[#e8b84b] text-[#e8b84b]' : 'text-stone-300'}`} viewBox="0 0 20 20" fill="currentColor">
                            <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                          </svg>
                        ))}
                      </div>
                      <span className="text-xs text-[#7a7468] ml-1">
                        ({course.enrollmentCount?.toLocaleString()})
                      </span>
                    </div>
                  </div>
                </div>
              </Link>
            ))}
          </div>

          <div className="text-center mt-8">
            <Button size="lg" variant="outline" asChild className="border-2 border-[#1a6b3c] text-[#1a6b3c] hover:bg-[#1a6b3c] hover:text-white rounded-full font-semibold">
              <Link href="/courses">
                View All Courses
                <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Button>
          </div>
        </div>
      </section>

      {/* ═══════════════════════════════════════════════════════════
          GOLD CTA BAND
          ═══════════════════════════════════════════════════════════ */}
      <section className="py-16 md:py-24 bg-[#e8b84b]">
        <div className="container mx-auto px-4 sm:px-6 text-center">
          <p className="text-xs font-semibold uppercase tracking-widest text-[#111310]/60 mb-3">JOIN THE MOVEMENT</p>
          <h2 className="text-3xl sm:text-4xl md:text-5xl font-extrabold text-[#111310] mb-4 font-[family-name:var(--font-playfair)]">
            Learning for Everyone, Everywhere
          </h2>
          <p className="text-[#111310]/70 text-base md:text-lg mb-10 max-w-2xl mx-auto">
            Elimu Africa is more than a platform — it is a movement to ensure that every African learner, regardless of geography, income, or circumstance, has access to the education they deserve.
          </p>
          <div className="flex flex-col sm:flex-row justify-center gap-4">
            <Button size="lg" asChild className="bg-[#0d3d22] hover:bg-[#0a3019] text-white font-semibold px-8 rounded-full shadow-lg">
              <Link href="/register">Start Learning Free</Link>
            </Button>
            <Button size="lg" variant="ghost" asChild className="border-2 border-[#111310]/70 text-[#111310] hover:bg-[#111310]/10 font-semibold rounded-full">
              <Link href="/courses">Explore Courses</Link>
            </Button>
          </div>
        </div>
      </section>
    </div>
  );
}
